

GET {{baseUrl}}/api/assistant/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/assistant/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=id
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/assistant/save
Content-Type: application/json

{ "spa": [{ "id": 0, "created_at": "2000-01-01", "uid": "UID", "user_id": 0 }] }


###

POST {{baseUrl}}/api/assistant/del
Content-Type: application/json

{ "ids": [0] }


###

POST {{baseUrl}}/api/assistant/create
Content-Type: application/json

{
  "params": {
    "name": "NAME",
    "description": "DESCRIPTION",
    "instructions": "INSTRUCTIONS"
  }
}


###

GET {{baseUrl}}/api/chat/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/chat/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=id
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
	&params[from_id]=0
	&params[to_id]=0
	&params[user_id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/chat/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "from_id": 0,
      "content": "CONTENT",
      "to_id": 0
    }
  ]
}


###

POST {{baseUrl}}/api/chat/del
Content-Type: application/json

{ "ids": [0] }


###

GET {{baseUrl}}/api/chat/getChatList
	?
Content-Type: application/json

###

POST {{baseUrl}}/api/chat/chat
Content-Type: application/json

{ "params": { "content": "CONTENT" } }


###

GET {{baseUrl}}/api/thread/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/thread/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=id
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
	&params[user_id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/thread/save
Content-Type: application/json

{ "spa": [{ "id": 0, "created_at": "2000-01-01", "uid": "UID", "user_id": 0 }] }


###

POST {{baseUrl}}/api/thread/del
Content-Type: application/json

{ "ids": [0] }


###

POST {{baseUrl}}/api/thread/create
Content-Type: application/json

{}


###

GET {{baseUrl}}/api/user/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/user/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=id
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
	&params[name]=NAME
Content-Type: application/json

###

POST {{baseUrl}}/api/user/save
Content-Type: application/json

{ "spa": [{ "id": 0, "created_at": "2000-01-01", "name": "NAME" }] }


###

POST {{baseUrl}}/api/user/del
Content-Type: application/json

{ "ids": [0] }


###

POST {{baseUrl}}/api/user/join
Content-Type: application/json

{ "params": { "name": "NAME" } }


###

GET {{baseUrl}}/api/user/me
	?
Content-Type: application/json

###

POST {{baseUrl}}/api/user/login
Content-Type: application/json

{ "params": { "name": "NAME" } }
