

GET {{baseUrl}}/api/chat/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/chat/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=id
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/chat/save
Content-Type: application/json

{
  "spa": [
    { "id": 0, "created_at": "2000-01-01", "user_id": 0, "content": "CONTENT" }
  ]
}


###

POST {{baseUrl}}/api/chat/del
Content-Type: application/json

{ "ids": [0] }


###

GET {{baseUrl}}/api/user/findById
	?subset=A
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/user/findMany
	?subset=A
	&params[num]=24
	&params[page]=1
	&params[search]=id
	&params[keyword]=KEYWORD
	&params[orderBy]=id-desc
	&params[queryMode]=both
	&params[id]=0
	&params[name]=NAME
Content-Type: application/json

###

POST {{baseUrl}}/api/user/save
Content-Type: application/json

{ "spa": [{ "id": 0, "created_at": "2000-01-01", "name": "NAME" }] }


###

POST {{baseUrl}}/api/user/del
Content-Type: application/json

{ "ids": [0] }


###

POST {{baseUrl}}/api/user/login
Content-Type: application/json

{ "name": "NAME" }
